Default: &defaults
  database: worker-demo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: worker-demo_test.sqlite3
  <<: *defaults

Staging:
  database: worker-demo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: worker-demo_production.sqlite3
  poolsize: 100
  <<: *defaults
